imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: retromat_plan_titles.yml }
    - { resource: retromat_sources.yml }

framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enabled: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        handler_id:  session.handler.native_file
        save_path:   '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments:       ~
    http_method_override: true
    assets: ~
    cache:
        app: cache.adapter.redis
        default_redis_provider: "redis://%redis_connection%"
        prefix_seed: "retromat"

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        unix_socket: "%database_socket%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                query_cache_driver:
                    type: service
                    id: retromat.doctrine_cache.redis
                metadata_cache_driver:
                    type: service
                    id: retromat.doctrine_cache.redis
                result_cache_driver:
                    type: service
                    id: retromat.doctrine_cache.redis

doctrine_migrations:
    dir_name: "%kernel.project_dir%/app/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

knp_doctrine_behaviors:
    translatable:   true

swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    encryption: "%mailer_encryption%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }

presta_sitemap:
    timetolive: 3600

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%retromat_backend_mail%"
        sender_name: "%retromat_backend_mail%"
    registration:
        confirmation:
            enabled: true

fos_rest:
    routing_loader:
        default_format: json
    format_listener: true
    view:
        view_response_listener: 'force'
    body_listener: true

# Parameters that are the same for each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # added for the presta sitemap command, but used elsewhere as well
    # http://symfony.com/doc/current/console/request_context.html
    router.request_context.host:   plans-for-retrospectives.com
    router.request_context.scheme: https
    activityFileNames:
        de: "%kernel.root_dir%/../web/static/lang/activities_de.js"
        en: "%kernel.root_dir%/../web/static/lang/activities_en.js"
        es: "%kernel.root_dir%/../web/static/lang/activities_es.js"
        fr: "%kernel.root_dir%/../web/static/lang/activities_fr.js"
        nl: "%kernel.root_dir%/../web/static/lang/activities_nl.js"
#        ru: "%kernel.root_dir%/../web/static/lang/activities_ru.js"