security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: team_dashboard
                always_use_default_target_path: true
            logout:
                path: fos_user_security_logout
                target: fos_user_security_login
            anonymous: true
        dev:
            # disables authentication for assets and the profiler, adapt it according to your needs
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    role_hierarchy:
        ROLE_TRANSLATOR_EN:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_DE:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_ES:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_FR:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_NL:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_PT-BR:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR_RU:
            - ROLE_TRANSLATOR
        ROLE_TRANSLATOR:
            - ROLE_USER
        ROLE_ADMIN:
            - ROLE_TRANSLATOR_EN
            - ROLE_TRANSLATOR_DE
            - ROLE_TRANSLATOR_ES
            - ROLE_TRANSLATOR_FR
            - ROLE_TRANSLATOR_NL
            - ROLE_TRANSLATOR_RU
    access_control:
        - { path: ^/(.+)/register, role: ROLE_ADMIN }
