dist: trusty
sudo: false
services:
  - mysql
  - redis-server

language: php

php:
    - 7.1

before_install:
    - cp backend/app/config/parameters.yml.travis backend/app/config/parameters.yml

install:
    - composer install --working-dir=backend

before_script:
    - php backend/bin/console doctrine:database:create
    - php backend/bin/console doctrine:migrations:migrate --no-interaction
    - php backend/bin/console retromat:import:activities
    - backend/bin/travis-ci/generate-templates-from-retromat-v1.sh

script:
    - backend/vendor/bin/simple-phpunit -c backend

deploy:
    on:
        branch: master
        condition: $TRAVIS_PHP_VERSION = 7.1
    skip_cleanup: true
    provider: script
    script: /bin/true

before_deploy:
    - mkdir -p .travis/
    - openssl aes-256-cbc -d -a -in backend/bin/travis-ci/rsa_travis_timon.enc -out .travis/rsa_travis_timon -k $travis_key
    - chmod 600 .travis/rsa_travis_timon
    - eval "$(ssh-agent -s)"
    - ssh-add .travis/rsa_travis_timon
    - rm -rf .travis/
    - openssl aes-256-cbc -d -a -in backend/app/config/parameters.yml.avior.enc -out backend/app/config/parameters.yml -k $travis_key
    - php backend/bin/travis-ci/deploy.php $TRAVIS_COMMIT
    - ssh-agent -k

notifications:
    on_success: always
    on_failure: always
    email:
        recipients:
            - timon.fiddike@agile.coach
#            - corinna@finding-marbles.com